### ISSUE TITLE
Old version works on file new version says this:

### ISSUE THREAD

**Issue by jonathancolledge** [remisalmon/gpx_interpolate#14]
(gpxenv) C:\Users\Jonathan>"C:\Users\Jonathan\Downloads\gpx-interpolate-master\gpx-interpolate-master\gpx_interpolate.py" -r 1 -s "C:\Users\Jonathan\Downloads\GpxResolutionSample\Test.gpx"
Read 482 trackpoints from C:\Users\Jonathan\Downloads\GpxResolutionSample\Test.gpx
Traceback (most recent call last):
  File "C:\Users\Jonathan\Downloads\gpx-interpolate-master\gpx-interpolate-master\gpx_interpolate.py", line 245, in <module>
    main()
  File "C:\Users\Jonathan\Downloads\gpx-interpolate-master\gpx-interpolate-master\gpx_interpolate.py", line 240, in main
    gpx_write(output_file, gpx_data_interp, write_speed=args.speed)
  File "C:\Users\Jonathan\Downloads\gpx-interpolate-master\gpx-interpolate-master\gpx_interpolate.py", line 182, in gpx_write
    raise ValueError('tstamp data is missing from gpx_data')
ValueError: tstamp data is missing from gpx_data

Files is here:
[Test.zip](https://github.com/remisalmon/gpx-interpolate/files/9740805/Test.zip)

**Comment by remisalmon** [comment]
This should be fixed with 2d20bdeea028d9bc9ad7c763bf9477a4c171651c, thanks for opening an issue!

**Comment by jonathancolledge** [comment]
Thanks!
